name: Create release

on:
  workflow_call:
    secrets:
      token:
        required: true
    outputs:
      releaseid:
        description: "returns the pullrequest number"
        value: ${{ jobs.generate_infos.outputs.release-id }}
      release-id:
        description: "returns the pullrequest number"
        value: ${{ jobs.generate_infos.outputs.release-id }}
      sha:
        description: "returns the sha from pull request"
        value: ${{ jobs.generate_infos.outputs.sha }}
      repo:
        description: "returns the repo name"
        value: ${{ jobs.generate_infos.outputs.repo }}
      owner:
        description: "returns the owner"
        value: ${{ jobs.generate_infos.outputs.owner }}
      sha-short:
        description: "returns the short sha from pull request"
        value: ${{ jobs.generate_infos.outputs.sha-short }}
      version:
        description: "returns the version to build"
        value: ${{ jobs.generate_infos.outputs.version }}
      latest-version:
        description: "returns the last release version"
        value: ${{ jobs.generate_infos.outputs.latest-version }}

jobs:
  generate_infos:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.tag.outputs.ACI_PR_SHA }}
      repo: ${{ steps.tag.outputs.ACI_REPO }}
      owner: ${{ steps.tag.outputs.ACI_OWNER }}
      sha-short: ${{ steps.tag.outputs.ACI_PR_SHA_SHORT }}
      version: ${{ steps.tag.outputs.ACI_NEXT_VERSION }}
      latest-version: ${{ steps.tag.outputs.ACI_LATEST_VERSION }}
      next-version: ${{ steps.tag.outputs.ACI_NEXT_VERSION }}
      release-id: ${{ steps.tag.outputs.ACI_RELEASE_ID }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: create release
        id: tag
        run: awesome-ci release create --merge-sha ${{ github.sha }} > $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
