name: Generate infos for PR

on:
  workflow_call:
    inputs:
      prnumber:
        description: "send the pullrequest number (optional)"
        default: ${{ github.event.pull_request.number }}
        required: false
        type: string
    secrets:
      token:
        required: true
    outputs:
      pr:
        description: "returns the pullrequest number"
        value: ${{ jobs.generate_infos.outputs.pr }}
      sha:
        description: "returns the sha from pull request"
        value: ${{ jobs.generate_infos.outputs.sha }}
      repo:
        description: "returns the repo name"
        value: ${{ jobs.generate_infos.outputs.repo }}
      owner:
        description: "returns the owner"
        value: ${{ jobs.generate_infos.outputs.owner }}
      sha-short:
        description: "returns the short sha from pull request"
        value: ${{ jobs.generate_infos.outputs.sha-short }}
      version:
        description: "returns the version to build"
        value: ${{ jobs.generate_infos.outputs.version }}

jobs:
  generate_infos:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.tag.outputs.pr }}
      sha: ${{ steps.tag.outputs.sha }}
      repo: ${{ steps.tag.outputs.repo }}
      owner: ${{ steps.tag.outputs.owner }}
      sha-short: ${{ steps.tag.outputs.sha-short }}
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: collect infos
        run: awesome-ci pr info -number ${{ inputs.prnumber }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
      - name: export infos
        id: tag
        shell: bash
        run: |
          echo "::set-output name=version::${ACI_VERSION}-PR-${ACI_PR}-${ACI_PR_SHA_SHORT}"
          echo "::set-output name=pr::$ACI_PR"
          echo "::set-output name=sha::$ACI_PR_SHA"
          echo "::set-output name=sha-short::$ACI_PR_SHA_SHORT"
          echo "::set-output name=owner::$ACI_OWNER"
          echo "::set-output name=repo::$ACI_REPO"
